# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - docker-cache
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: build docker image
      script:
      - echo $DOCKER_PASSWORD
      - echo $DOCKER_USERNAME
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo 'logged in to docker'
      - if [[ -f /var/lib/docker-cache/base.tar ]]; then docker load -i /var/lib/docker-cache/base.tar; fi;
      - docker images


before_cache:
  - docker images
  - docker save translate/pootle:base -o docker-cache/base.tar
  - ls -lh docker-cache
