# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - docker-cache
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: Build test env
       script:
       - if [[ -f /var/lib/docker-cache/base.tar ]]; then sudo docker load -i /var/lib/docker-cache/base.tar; fi;
       - docker images
       - whoami
       - git clone https://github.com/phlax/pootle pootle_env
       - cd pootle_env
       - git checkout docker-dev
       - pip install -r requirements/host.txt
       - export LOCAL_USER_ID=$UID
       - makey build-all
       - makey run bash make travis-assets
    - stage: test
      script:
      - # makey test-py-postgres
      - echo 'success!'

before_cache:
  - docker images
  - docker save translate/pootle:base -o docker-cache/base.tar
  - ls -lh docker-cache
