# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: Build docker environment
      script:
      - git clone https://github.com/phlax/pootle pootle_env
      - cd pootle_env && git checkout docker-dev && ./docker/bin/build-travis-images
    - stage: Run tests
      script:
      - git clone https://github.com/phlax/pootle pootle_env
      - cd pootle_env && git checkout docker-dev && ./docker/bin/run-travis-sqlite
      script:
      - git clone https://github.com/phlax/pootle pootle_env
      - cd pootle_env && git checkout docker-dev && ./docker/bin/run-travis-sqlite
