# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - $HOME/docker-cache
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: Build docker environment
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - if [[ -f $HOME/docker-cache/base.tar ]]; then docker load -i $HOME/docker-cache/base.tar; fi;
      - docker images
      - git clone https://github.com/phlax/pootle pootle_env
      - cd pootle_env
      - git checkout docker-dev
      - pip install -r requirements/host.txt
      - export LOCAL_USER_ID=$UID
      - makey build-all
      - makey run bash make travis-assets
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/pootle:base
    - stage: Run sqlite tests
      script:
      - docker images

before_cache:
  - docker images
  - mkdir -p $HOME/docker-cache
  - docker save translate/pootle:base -o $HOME/docker-cache/base.tar
  - ls -lh $HOME/docker-cache
