# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: Build docker environment
      script:
      - docker pull $DOCKER_USERNAME/pootle:dev
      - docker tag $DOCKER_USERNAME/pootle:base translate/pootle:base
      - docker images
      - git clone https://github.com/phlax/pootle pootle_env
      - cd pootle_env
      - git checkout docker-dev
      - pip install -r requirements/host.txt
      - export LOCAL_USER_ID=$UID
      - makey build-all
      - makey run bash make travis-assets
      - docker images
      - mkdir -p $HOME/docker-cache
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag translate/pootle:base $DOCKER_USERNAME/pootle:base
      - docker push $DOCKER_USERNAME/pootle:base
    - stage: Run sqlite tests
      script:
      - docker pull $DOCKER_USERNAME/pootle:base
      - docker images
