# https://travis-ci.org/#!/translate/pootle
dist: trusty
sudo: true
language: python
services:
  - docker

cache:
  directories:
    - docker-cache
    - $HOME/virtualenv/python2.7.14/bin
    - $HOME/virtualenv/python2.7.14/lib
    - $HOME/virtualenv/python2.7/bin

jobs:
  include:
    - stage: Build test env
       script:
       - echo 'installing'
    - stage: test
      script:
      - # makey test-py-postgres
      - echo 'success!'

before_cache:
  - docker images
  - docker save translate/pootle:base -o docker-cache/base.tar
  - ls -lh docker-cache
